#!/bin/bash

tmux -2 new-session -s SFTPD -d  -n "local" -c /home/mskelton/Code/sk3l/openssh-portable 
tmux -2 new-window -n "src" -c /home/mskelton/Code/sk3l/openssh-portable 
tmux -2 select-window -t "src"
tmux -2 split-window  -v -c /home/mskelton/Code/sk3l/openssh-portable -t 1 vim 
tmux -2 split-window  -v -c /home/mskelton/Code/sk3l/openssh-portable -t 2 vifm 
tmux -2 kill-pane -t 1
tmux -2 new-window -n "bld" -c /home/mskelton/Code/sk3l/openssh-portable
tmux -2 new-window -n "run" -c /home/mskelton/Code/sk3l/openssh-portable
tmux -2 select-window -t "local"
tmux attach-session -t SFTPD 

