#!/bin/bash

if [ $# != 3 ]; then
   echo $'\n'
   echo "Usage: mux-psql <srcdir> <nginxStart> <gunicornStart>"
   echo $'\n'
   exit 16
fi

tmux new-session -s SKELONL -d 
TERM=screen-256color tmux -2 new-window -n SKELONL-main -c $1 vim
tmux split-window -h -c $1 $2 
tmux selectp -t 1 
tmux split-window -v -c $1 
tmux selectp -t 3
tmux split-window -v -c $1 $3 
tmux selectp -t 1
tmux attach-session -t SKELONL

